config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'

  get '/signup', to: 'users#new'

  get '/help', to: 'static_pages#help' 

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  root 'static_pages#home'

  post '/signup' , to: 'users#create'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy' 

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :account_activations, only: [:edit]

  resources :pwd_resets,          only: [:edit, :new, :create, :update]

  resources :mps,                 only: [:create, :destroy]

  resources :relationships,       only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token, :activation_token, :reset_token
	before_save { email.downcase! }
    before_create :create_activation_digest
	validates :name,  presence: true, length: { maximum: 50 }
	regex = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, 
	                  format: { with: regex } , 
	                  uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }  , allow_nil: true
    has_many :mps, dependent: :destroy
    has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
    has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
    has_many :following, through: :active_relationships,  source: :followed
    has_many :followers, through: :passive_relationships, source: :follower                           

	def User.digest(string)
	 cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST:
	                                               BCrypt::Engine.cost
	 BCrypt::Password.create(string, cost: cost)
    end   


    def self.new_token
    	SecureRandom.urlsafe_base64
    end

    def remember
    	self.remember_token = User.new_token
    	update_attribute(:remember_digest,User.digest(remember_token))
    end

    def authenticated?(attribute,token)
    	digest = send("#{attribute}_digest")
        return false if digest.nil?
    	BCrypt::Password.new(digest) == token
    end

    def forget
    	update_attribute(:remember_digest, nil)
    end

    def activate
        update_attribute(:activated, true)
        update_attribute(:activated_at, Time.zone.now)
    end

    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end

    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest, User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end

    def send_pwd_reset_email
        UserMailer.pwd_reset(self).deliver_now
    end

    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

    def feed
        following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
        Mp.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
    end

    def follow(other_user)
        active_relationships.create(followed_id: other_user.id)
    end

    # 取消关注另一个用户
    def unfollow(other_user)
         active_relationships.find_by(followed_id: other_user.id).destroy
    end

    # 如果当前用户关注了指定的用户，返回 true
    def following?(other_user)
         following.include?(other_user)
    end

    private 
        def create_activation_digest
            self.activation_token = User.new_token
            self.activation_digest = User.digest(activation_token)
        end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only:[:destroy]
	
  def show
  	@user = User.find(params[:id])
    @mps = @user.mps.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      @user.send_activation_email
  		flash[:info] = "Please check your email to activate your account"
  		redirect_to root_url
  	else
  		render "new"

  	end
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if  @user.update_attributes(user_params)
      redirect_to @user
      flash[:success] = "Profile Updated"
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:sucess] = 'User deleted'
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end



  private
    def user_params
    	params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end


    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
    end

    def admin_user
      redirect_to users_url if !current_user.admin?
      flash[:damger] = "You are not the admin"
    end




end

app/helpers/user_helper.rb
module UserHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar",size: 40)
	end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
		<%= render "shared/error_messages" %>
		<%= f.label :name %>
		<%= f.text_field :name, class: "form_control" %>

		<%= f.label :email %>
		<%= f.email_field :email, class: "form_control" %>

		<%= f.label :password %>
		<%= f.password_field :password, class: "form_control" %>

		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation, class: "form_control" %>

		<%= f.submit yield(:button_text), class: "btn btn-primary"%>

<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title,"Edit user") %>
<% provide(:button_text,"Update") %>
<h1>Update Your Profile</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3" >
	<%= render 'form' %>
		<div class="gravatar_edit">
	    	<%= gravatar_for @user %>
	    	<a href="http://gravatar.com/emails" target="_blank">change</a>
	    </div>
	 </div>
</div>	 

app/views/users/index.html.erb
<% provide(:title,"All users") %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
	<% @users.each do |usr| %>

	<li>
		<%= gravatar_for usr%>
		<%= link_to usr.name, user_path(id: usr.id) %>
		<% if current_user.admin? && !current_user?(usr) %>
   		 | <%= link_to "delete", usr, method: :delete,
                                  data: { confirm: "You sure?" } %>
		   <% end %>
	</li>
	<% end %>
</ul>		

<%= will_paginate @users %>
<script>
	var options = {
	    alignment:"center",//居中显示
	    currentPage: pageIndex,//当前页数
	    totalPages: total,//总页数 注意不是总条数
	    itemTexts:Next-->下一页
	    pageUrl: function(type, page, current){
	            if (page==current) {
	                return "javascript:void(0)";
	            } else {
	                return "/Articles?pageSize=15&pageIndex="+page;
	            }
	        }
	}
	$("#true").bootstrapPaginator(options);
</script>

app/views/users/new.html.erb
<% provide(:title, "Signup")%>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
    <%= render "shared/error_messages", object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confrimation, class: 'form-control' %>

    <%= f.submit "Create", class: "btn btn-primary" %>
    



    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
  <%= render 'follow_form' if logged_in? %>
    <% if @user.mps.any? %>
      <h3>Microposts (<%= @user.mps.count %>)</h3>
      <ol class="mps">
        <%= render @mps %>
      </ol>
      <%= will_paginate @mps %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.mps.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>