config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'

  get '/signup', to: 'users#new'

  get '/help', to: 'static_pages#help' 

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  root 'static_pages#home'

  post '/signup' , to: 'users#create'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy' 

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :account_activations, only: [:edit]

  resources :pwd_resets,          only: [:edit, :new, :create, :update]

  resources :mps,                 only: [:create, :destroy]

  resources :relationships,       only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/pwd_resets_controller.rb
class PwdResetsController < ApplicationController
  before_action :get_user,          only: [:edit, :update]
  before_action :valid_user,        only: [:edit, :update]
  before_action :check_expiration,  only: [:edit, :update]

  def new

  end

  def edit
  end

  def create

  	@user = User.find_by(email: params[:pwd_reset][:email].downcase)
  	if @user
  		@user.create_reset_digest
  		@user.send_pwd_reset_email
  		flash[:info] = "Email sent with password reset instructions"
  		redirect_to root_url
  	else
  		flash[:danger] = "Email address not found"
  		redirect_to root_url
  	end

  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "Password has been reset."
      redirect_to @user
    else
      render 'edit'
    end
  end

    private
      def user_params
        params.require(:user).permit(:password, :password_confirmation)
      end

      def get_user
        @user = User.find_by(email: params[:email])
      end

      def check_expiration
        if @user.password_reset_expired?
          flash[:danger] = "Password reset has expired"
          redirect_to new_pwd_reset_url
        end
      end

      def valid_user
        unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
          redirect_to root_url
        end
      end
    
end

app/helpers/pwd_resets_helper.rb
module PwdResetsHelper
end

app/views/pwd_resets/edit.html.erb
<% provide(:title, "Password Reset") %>
<h1>Password Reset</h1>


<div class="row">
	<div class="col-md-4 col-md-offset-5">
	<%= form_for(@user, url: edit_pwd_reset_path(params[:id])) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

    <%= hidden_field_tag :email, @user.email %>

	<%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Submit",class: "btn btn-primary" %>
    <% end %>
    </div>
 </div>

app/views/pwd_resets/new.html.erb
<% provide(:title, "Passwrod reset") %>
<h1>Forget Password</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
	<%= form_for(:pwd_reset, url: pwd_resets_path) do |f| %>

	<%= f.label :email %>
	<%= f.email_field :email, class: "form-control" %>

	<%= f.submit "Submit", class: "btn btn-primary" %>
	<% end %>
	</div>
</div>